<?php

/**
 * @file
 * Typogrify: Brings typographical refinemnts to drupal
 *
 * Hook together all the typogrify components.
 */
namespace Drupal\typogrify;

use Drupal\Core\Link;
use \Drupal\Core\Url;

define('PHP_TYPOGRIFY_VERSION', '1.0');

/**
 * Implements hook_filter_info_alter().
 */
function typogrify_filter_info_alter(&$info) {
  $info = [
    'typogrify' => [
      'title' => t('Typogrify'),
      'description' => t('Adds typographic refinements.'),
      'process callback' => '_typogrify_process',
      'settings callback' => '_typogrify_settings',
      'default settings' => [
        'smartypants_enabled' => 1,
        'smartypants_hyphens' => 3,
        'space_hyphens' => 0,
        'wrap_ampersand' => 1,
        'widont_enabled' => 1,
        'space_to_nbsp' => 1,
        'hyphenate_shy' => 0,
        'wrap_abbr' => 0,
        'wrap_caps' => 1,
        'wrap_initial_quotes' => 1,
        'wrap_numbers' => 0,
        'ligatures' => [],
        'arrows' => [],
        'fractions' => [],
        'quotes' => [],
      ],
      'tips callback' => '_typogrify_filter_tips',
    ],
  ];
}

